build:
  image: golang
  commands:
    - go get -v
    - go build -v
    - go get -v github.com/hashicorp/logutils
    - go test -v ./...
publish:
  gcs:
    auth_key: "$$SERVICE_ACCOUNT_KEY"
    source: terraform-provider-lxd
    target: $$PUBLISH_BUCKET/bin/terraform-provider-lxd
    acl:
      - project-owners-$$PROJECT_UID:OWNER
      - project-viewers-$$PROJECT_UID:READER
    when:
      repo: mmorrison/terraform-provider-lxd
      branch: master
  gcs:
    auth_key: "$$SERVICE_ACCOUNT_KEY"
    source: terraform-provider-lxd
    target: $$PUBLISH_BUCKET/builds/terraform-provider-lxd/$$COMMIT/terraform-provider-lxd
    acl:
      - project-owners-$$PROJECT_UID:OWNER
      - project-viewers-$$PROJECT_UID:READER
    when:
      repo: mmorrison/terraform-provider-lxd
      branch: master
